### ISSUE TITLE
Using InputReader in Day statically

### ISSUE THREAD

**Issue by DaFunkl** [hughjdavey/aoc-kotlin-starter#1]
I had to put the function of InputReader in a companion object to access the functions in a "static" way.
eg:

``` kotlin
class InputReader {

    companion object {
        fun getInputAsString(day: Int) = fromResources(day).readText()


        fun getInputAsList(day: Int) = fromResources(day).readLines()

        private fun fromResources(day: Int): File {
            return File(javaClass.classLoader.getResource("input_day_$day.txt").toURI())
        }
    }
}
```

alternative would be to change the access to  
``` kotlin
protected val inputList: List<String> by lazy { InputReader().getInputAsList(dayNumber) }
```

I've copy pasted the files instead of cloning, maybe I missed some configuration preventing this error

**Comment by hughjdavey** [comment]
Hi thanks for raising. What do you mean access the functions in a static way? Can you post some code that tried to access `inputList` or `inputString` and failed? If you look at the sample `Day1.kt` that comes in the project you'll see it accessing both those variables. Do you mean you're trying to access them in e.g. a companion object of `Day1`?

**Comment by hughjdavey** [comment]
Ah hold on I might see the issue. It should be `object InputReader` (i.e. already 'static') but I see in the code you posted you have it as a `class`.

**Comment by DaFunkl** [comment]
My fault, 
thanks for your insight
